# Generated by Django 5.0.2 on 2024-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='does_karting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plays_darts',
            field=models.BooleanField(default=True),
        ),
    ]
