# Generated by Django 5.0.7 on 2024-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['id'], name='user_id_index'),
        ),
    ]
