# Generated by Django 5.0.7 on 2024-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_customuser_plays_darts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plays_darts',
            field=models.BooleanField(default=True),
        ),
    ]
