# Generated by Django 5.0.2 on 2024-06-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='headshot',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
