# Generated by Django 5.0.6 on 2024-06-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='headshots/'),
        ),
    ]
