# Generated by Django 5.0.6 on 2024-07-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='headshot',
        ),
    ]
