# Generated by Django 5.0.7 on 2024-07-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_id_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='user_id_index',
            old_name='id_index',
        ),
    ]
