version: '3.7'

services:
  web:
    build: .
    command: gunicorn darts_portal.wsgi -b 0.0.0.0:8000
    environment:
      - SECRET_KEY=^+v=tpcw8e+aq1zc(j-1qf5%w*z^a-5*zfjeb!jxy(t=zv*bdg
      - ENVIRONMENT=production
      - LOCKDOWN_ENABLED=True
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
