# Generated by Django 5.0 on 2023-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('winner', models.CharField(max_length=200)),
                ('runner_up', models.CharField(max_length=200)),
            ],
        ),
    ]
