# Generated by Django 5.0 on 2023-12-12 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='runner_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_up', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='win',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
