# Generated by Django 5.0 on 2023-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0003_alter_win_runner_up_alter_win_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
