# Generated by Django 5.0 on 2023-12-14 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0005_win_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='participants',
            field=models.ManyToManyField(related_name='games_played', to=settings.AUTH_USER_MODEL),
        ),
    ]
