# Generated by Django 5.0.1 on 2024-01-03 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0006_alter_win_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
