# Generated by Django 5.0.1 on 2024-01-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0007_alter_win_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
