# Generated by Django 5.0.7 on 2024-07-30 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0009_champion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='win',
            index=models.Index(fields=['id'], name='win_id_index'),
        ),
    ]
